# Analisis de ventas
## Lectura de datos:

In [1]:
import pandas as pd

In [2]:
datos1 = pd.read_csv("./Datos_Ventas_Tienda.csv")
datos2 = pd.read_csv("./Datos_Ventas_Tienda2.csv")

df1 = pd.DataFrame(datos1)
df2 = pd.DataFrame(datos2)
df1

         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    1/17/2023  Electrónic         7              200         1400
1     9/1/2023  Electrónic         8              200         1600
2    7/29/2023    Juguetes         3               30           90
3    10/4/2023   Alimentos         4               10           40
4    2/28/2023  Electrónic         6              200         1200
..         ...         ...       ...              ...          ...
995  4/27/2023   Alimentos         2               10           20
996   6/9/2023        Ropa        10               50          500
997  8/21/2023   Alimentos         8               10           80
998  3/28/2023  Electrónic         6              200         1200
999   3/7/2023  Electrónic         4              200          800

[1000 rows x 5 columns]

In [3]:
df2

         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    8/25/2023  Electrónic         5              200         1000
1    8/14/2023   Alimentos         9               10           90
2    8/30/2023        Ropa         6               50          300
3    11/9/2023   Alimentos         2               10           20
4   10/26/2023        Ropa         8               50          400
5    12/1/2023    Juguetes         2               30           60
6    5/16/2023  Electrónic         4              200          800
7     2/9/2023      Libros         1               20           20
8     1/9/2023  Electrónic         2              200          400
9     5/3/2023  Electrónic         6              200         1200
10  11/30/2023  Electrónic         5              200         1000
11  10/26/2023  Electrónic         1              200          200
12   8/22/2023    Juguetes         3               30           90
13    6/5/2023  Electrónic         1              200          200
14   10/2/2023    Juguetes         6               30          180
15   1/25/2023  Electrónic         3              200          600
16   5/20/2023        Ropa         4               50          200
17   4/29/2023   Alimentos         8               10           80
18  12/20/2023        Ropa         2               50          100
19   4/10/2023        Ropa         8               50          400
20   5/19/2023    Juguetes         5               30          150
21    2/3/2023  Electrónic         4              200          800
22    3/4/2023        Ropa         5               50          250
23  11/12/2023    Juguetes         7               30          210
24   5/22/2023      Libros         7               20          140
25  11/19/2023        Ropa         4               50          200
26   7/31/2023   Alimentos         6               10           60
27  10/11/2023        Ropa         6               50          300
28   12/9/2023    Juguetes         4               30          120
29    3/6/2023      Libros         9               20          180
30   3/27/2023   Alimentos         1               10           10
31   4/23/2023        Ropa         9               50          450
32   5/26/2023  Electrónic         6              200         1200
33   1/20/2023    Juguetes         5               30          150
34   3/22/2023   Alimentos         9               10           90
35   2/26/2023      Libros         9               20          180
36   7/30/2023    Juguetes         1               30           30
37  11/18/2023        Ropa         3               50          150
38   6/20/2023      Libros         8               20          160
39    6/6/2023      Libros         3               20           60
40    5/2/2023   Alimentos         5               10           50
41    8/7/2023  Electrónic         9              200         1800
42  11/18/2023    Juguetes         8               30          240
43   1/17/2023    Juguetes         8               30          240
44  10/10/2023      Libros         6               20          120
45   9/11/2023    Juguetes        10               30          300
46    1/3/2023    Juguetes        10               30          300
47   11/7/2023   Alimentos         3               10           30
48   8/20/2023  Electrónic         6              200         1200
49   7/21/2023    Juguetes         3               30           90

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            1000 non-null   object
 1   Producto         1000 non-null   object
 2   Cantidad         1000 non-null   int64
 3   Precio Unitario  1000 non-null   int64
 4   Total Venta      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fecha            50 non-null     object
 1   Producto         50 non-null     object
 2   Cantidad         50 non-null     int64
 3   Precio Unitario  50 non-null     int64
 4   Total Venta      50 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.1+ KB

## Fusion de datos:

In [38]:
df_ventas = pd.concat([df1,df2], ignore_index= True)
df_ventas

          Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0     1/17/2023  Electrónic         7              200         1400
1      9/1/2023  Electrónic         8              200         1600
2     7/29/2023    Juguetes         3               30           90
3     10/4/2023   Alimentos         4               10           40
4     2/28/2023  Electrónic         6              200         1200
...         ...         ...       ...              ...          ...
1045  9/11/2023    Juguetes        10               30          300
1046   1/3/2023    Juguetes        10               30          300
1047  11/7/2023   Alimentos         3               10           30
1048  8/20/2023  Electrónic         6              200         1200
1049  7/21/2023    Juguetes         3               30           90

[1050 rows x 5 columns]

Ahora tenemos el DataFrame `df_ventas` con todos los datos no repetidos.

## Limpieza de datos:

In [39]:
df_ventas["Fecha"] = pd.to_datetime(df_ventas["Fecha"])
df_ventas["Fecha"]

0      2023-01-17
1      2023-09-01
2      2023-07-29
3      2023-10-04
4      2023-02-28
          ...
1045   2023-09-11
1046   2023-01-03
1047   2023-11-07
1048   2023-08-20
1049   2023-07-21
Name: Fecha, Length: 1050, dtype: datetime64[ns]

## Analisis de ventas:
#### Producto mas vendido:

In [54]:
producto_estrella = df_ventas.groupby("Producto")["Cantidad"].sum()
producto_estrella.head(1)

Producto
Alimentos    1262
Name: Cantidad, dtype: int64

#### Mes con mas ventas:

In [55]:
meses = []
for f in df_ventas["Fecha"]:
    meses.append(f.month)
df_ventas["Meses"] = meses
df_ventas

          Fecha    Producto  Cantidad  Precio Unitario  Total Venta  Meses
0    2023-01-17  Electrónic         7              200         1400      1
1    2023-09-01  Electrónic         8              200         1600      9
2    2023-07-29    Juguetes         3               30           90      7
3    2023-10-04   Alimentos         4               10           40     10
4    2023-02-28  Electrónic         6              200         1200      2
...         ...         ...       ...              ...          ...    ...
1045 2023-09-11    Juguetes        10               30          300      9
1046 2023-01-03    Juguetes        10               30          300      1
1047 2023-11-07   Alimentos         3               10           30     11
1048 2023-08-20  Electrónic         6              200         1200      8
1049 2023-07-21    Juguetes         3               30           90      7

[1050 rows x 6 columns]

In [58]:
mes_estrella = df_ventas.groupby("Meses")["Total Venta"].sum().sort_values(ascending = False)
mes_estrella.head(1)

Meses
8    45090
Name: Total Venta, dtype: int64

## Guardarlo en un .csv:

In [60]:
df_ventas.to_csv("Resumen_ventas.csv")