# Analisis de Medallas
## Manejo inicial de datos
Este apartado es mas para ver el DataFrame, ver los datos que maneja, limpiar datos y demas.

In [1]:
import pandas as pd
df = pd.read_csv("./medallas.csv")
df

     Oro  Plata  Bronce  Total          Pais
0    NaN    1.0     2.0      3     Argentina
1    NaN    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    NaN    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   NaN    1.0     NaN      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    NaN     2.0      5    Uzbekistan
92   1.0    3.0     NaN      4     Venezuela

[93 rows x 5 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [34]:
suma = df.sum()
print(suma)

Oro                                                   286.0
Plata                                                 329.0
Bronce                                                375.0
Total                                                   981
Pais      ArgentinaArmeniaAustraliaAustriaAzerbaijanBaha...
dtype: object

In [24]:
df_filtrado = df.fillna(0)
df_filtrado

     Oro  Plata  Bronce  Total          Pais
0    0.0    1.0     2.0      3     Argentina
1    0.0    2.0     2.0      4       Armenia
2   17.0    7.0    22.0     46     Australia
3    1.0    1.0     5.0      7       Austria
4    0.0    3.0     4.0      7    Azerbaijan
..   ...    ...     ...    ...           ...
88   0.0    1.0     0.0      1  Turkmenistan
89   2.0    1.0     1.0      4        Uganda
90   1.0    6.0    12.0     19       Ukraine
91   3.0    0.0     2.0      5    Uzbekistan
92   1.0    3.0     0.0      4     Venezuela

[93 rows x 5 columns]

In [36]:
df_unicos = df.drop_duplicates(subset = "Pais")
df_unicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Oro     65 non-null     float64
 1   Plata   69 non-null     float64
 2   Bronce  76 non-null     float64
 3   Total   93 non-null     int64
 4   Pais    93 non-null     object
dtypes: float64(3), int64(1), object(1)
memory usage: 3.8+ KB

In [41]:
df_filtrado.describe()

             Oro      Plata     Bronce       Total
count  93.000000  93.000000  93.000000   93.000000
mean    3.075269   3.537634   4.032258   10.548387
std     6.682613   6.598022   5.969946   18.897617
min     0.000000   0.000000   0.000000    1.000000
25%     0.000000   0.000000   1.000000    2.000000
50%     1.000000   1.000000   2.000000    4.000000
75%     3.000000   4.000000   4.000000    8.000000
max    39.000000  41.000000  33.000000  113.000000

## Filtrar por paises que tengan mas de 10 medallas:

In [42]:
filtro = df["Total"] >= 10
df[filtro].sort_values(by="Total", ascending = False)

     Oro  Plata  Bronce  Total                        Pais
25  39.0   41.0    33.0    113   Estados Unidos de America
72  38.0   32.0    18.0     88  Republica Popular de China
73   2.0   28.0    23.0     71                         ROC
34  22.0   21.0    22.0     65                Gran Bretana
46  27.0   14.0    17.0     58                       Japon
2   17.0    7.0    22.0     46                   Australia
32   1.0   11.0    16.0     37                     Germany
60   1.0   12.0    14.0     36                 Netherlands
30   1.0   12.0    11.0     33                      France
14   7.0    6.0    11.0     24                      Canada
11   7.0    6.0     8.0     21                      Brazil
90   1.0    6.0    12.0     19                     Ukraine
81   3.0    8.0     6.0     17                       Spain
19   7.0    3.0     5.0     15                        Cuba
66   4.0    5.0     5.0     14                      Poland
83   3.0    4.0     6.0     13                 Switzerland
87   2.0    2.0     9.0     13                      Turkey
15   2.0    4.0     6.0     12              Chinese Taipei
20   4.0    4.0     3.0     11              Czech Republic
21   3.0    4.0     4.0     11                     Denmark

## Mostrar los 3 paises con mas medallas de Oro:

In [19]:
df.sort_values(by="Oro", ascending=False).head(3)

     Oro  Plata  Bronce  Total                        Pais
25  39.0   41.0    33.0    113   Estados Unidos de America
72  38.0   32.0    18.0     88  Republica Popular de China
46  27.0   14.0    17.0     58                       Japon