In [2]:
import pandas as pd
df1 = pd.DataFrame({"id":[1, 2, 3, 5, 6], "nombre": ["Antonio", "Mario", "Eugenia", "Celia", "Carlos"]})
df2 = pd.DataFrame({"id":[1, 2, 3, 4, 5], "suscripcion_activa": [True, False, True, True, False]})
df1

   id  suscripcion_activa
0   1                True
1   2               False
2   3                True
3   4                True
4   5               False

In [3]:
df2

   id  suscripcion_activa
0   1                True
1   2               False
2   3                True
3   4                True
4   5               False

In [4]:
df_unidas = pd.merge(df1, df2, on= "id")
df_unidas

   id   nombre  suscripcion_activa
0   1  Antonio                True
1   2    Mario               False
2   3  Eugenia                True
3   5    Celia               False

## .merge
El atributo merge sirve para juntar DataFrames que compartan campo, el cual se indica con el campo `on`.<br> En caso de que un df tenga un valor y el otro no, no se guardará, es un `AND`.<br> Mas o menos es como una `foreign key`

In [5]:
df_todo = pd.merge(df1, df2, on="id", how="outer")
df_todo

   id   nombre suscripcion_activa
0   1  Antonio               True
1   2    Mario              False
2   3  Eugenia               True
3   4      NaN               True
4   5    Celia              False
5   6   Carlos                NaN

In [9]:
# Creación del DataFrame df_a
df_a = pd.DataFrame({
    'id': [1, 2, 3],
    'Nombre': ['Ana', 'Beto', 'Carla']
})
df_a.set_index('id', inplace=True)

# Creación del DataFrame df_b
df_b = pd.DataFrame({
    'id': [1, 2, 3],
    'Edad': [25, 30, 35]
})
df_b.set_index('id', inplace=True)
df_a

   Nombre
id
1     Ana
2    Beto
3   Carla

In [10]:
df_b

    Edad
id
1     25
2     30
3     35

In [12]:
df_combinado = df_a.join(df_b)
df_combinado

   Nombre  Edad
id
1     Ana    25
2    Beto    30
3   Carla    35

## .join
Tambien se pueden juntar los df con el atributo df, este se aplica sobre el df directamente y une uno principal con el secundario, es como si pusiesemos en el atributo merge el how = "left" puesto que da prioridad al primer df.<br>Algo a tener en cuenta de este atributo es que se basa no en los id, si no en los indices que tiene la tabla, por lo que habra que declararlos bien

In [15]:
import pandas as pd
productos_df = pd.DataFrame({
    'ProductoID': [1, 2, 3, 4],
    'Nombre': ['Producto 1', 'Producto 2', 'Producto 3', 'Producto 4'],
    'Precio': [100, 150, 200, 250]
})

productos_df = productos_df.set_index('ProductoID')

categorias_df = pd.DataFrame({
    'CategoriaID': [1, 2, 3],
    'NombreCategoria': ['Categoría 1', 'Categoría 2', 'Categoría 3']
}).set_index('CategoriaID')

df_combinado = productos_df.join(categorias_df, how="right")
df_combinado

                 Nombre  Precio NombreCategoria
CategoriaID
1            Producto 1     100     Categoría 1
2            Producto 2     150     Categoría 2
3            Producto 3     200     Categoría 3