# Limpieza de datos de un archivo

Primero que todo tenemos que iniciar los datos que queremos manipular

In [1]:
import pandas as pd
datos = {"fruta": ["Limones", "Cocos", "Melocotones", "Albaricoques", "Sandias", "Fresas"],
                  "precio": [2.6, 2.1, 3.6, None, 4.9, 7.5],
                  "cantidad_vendida": [52, 21, 65, 29, None, 33]
                  }
df = pd.DataFrame(datos)
df

          fruta  precio  cantidad_vendida
0       Limones     2.6              52.0
1         Cocos     2.1              21.0
2   Melocotones     3.6              65.0
3  Albaricoques     NaN              29.0
4       Sandias     4.9               NaN
5        Fresas     7.5              33.0

Como vemos, tenemos valores null en nuestras columnas, necesitamos limpiar esos datos de dos formas principalmente
1. Eliminarlos
2. Meter el promedio<br><br>Pero antes, para poder darnos cuenta si tenemos una gran cantidad de datos usaremos lo siguiente:

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fruta             6 non-null      object
 1   precio            5 non-null      float64
 2   cantidad_vendida  5 non-null      float64
dtypes: float64(2), object(1)
memory usage: 276.0+ bytes

Esto nos puede mostrar los campos no nulos que hay por columnas y la cantidad de entradas que ha de haber,<br>
si estas no coinciden, quiere decir que hay campos nulos, por lo que debemos hacer limpieza.

### Rellenarlos con promedio

In [3]:
valores_nuevos = {"precio":df["precio"].mean(), "cantidad_vendida": 0}
df_rellenados = df.fillna(valores_nuevos)
df_rellenados

          fruta  precio  cantidad_vendida
0       Limones    2.60              52.0
1         Cocos    2.10              21.0
2   Melocotones    3.60              65.0
3  Albaricoques    4.14              29.0
4       Sandias    4.90               0.0
5        Fresas    7.50              33.0

In [4]:
df_rellenados["cantidad_vendida"] = df_rellenados["cantidad_vendida"].astype(int)
df_rellenados

          fruta  precio  cantidad_vendida
0       Limones    2.60                52
1         Cocos    2.10                21
2   Melocotones    3.60                65
3  Albaricoques    4.14                29
4       Sandias    4.90                 0
5        Fresas    7.50                33

Se puede tambien limpiar datos duplicados, vamos a crear un nuevo df

In [5]:
datos = {"id" : [1, 2, 2, 3, 4],
         "precio" : [2.3, 36.5, 36.5, 25.4, 5.5],
         "en_almacen" : [12, 6, 0, 5, 4]}
df_unicos = pd.DataFrame(datos)
df_unicos

   id  precio  en_almacen
0   1     2.3          12
1   2    36.5           6
2   2    36.5           0
3   3    25.4           5
4   4     5.5           4

Podemos ver como el id 2 es igual solo que tienen valores diferentes en almacén, por ello tendremos que especificar el campo que queremos que se fije para los duplicados:

In [6]:
df_unicos = df_unicos.drop_duplicates(subset = "id")
df_unicos

   id  precio  en_almacen
0   1     2.3          12
1   2    36.5           6
3   3    25.4           5
4   4     5.5           4

## Conclusión:
Así tendríamos los datos limpios para poder hacer cualquier tipo de análisis. <br>
Obviamente no aplica a todos los casos, puesto que cada uno es un mundo, pero a la gran mayoría sí. <br><br>
Muchas gracias por leer.